// flow-typed signature: 0588520b57c1319dda265bdc2a8ce3f5
// flow-typed version: <<STUB>>/proton-native_vlatest/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'proton-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'proton-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'proton-native/bin/components/App' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/Area' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/Button' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/Checkbox' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/ColorButton' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/Combobox' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/DesktopComponent' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/Dialog' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/EditableCombobox' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/Entry' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/FontButton' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/Form' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/Grid' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/Group' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/HorizontalBox' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/HorizontalSeparator' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/index' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/MenuBar' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/MultilineEntry' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/PasswordEntry' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/ProgressBar' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/RadioButton' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/Root' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/Slider' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/Spinbox' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/Tab' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/Text' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/VerticalBox' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/VerticalSeparator' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/View' {
  declare module.exports: any;
}

declare module 'proton-native/bin/components/Window' {
  declare module.exports: any;
}

declare module 'proton-native/bin/constants/types' {
  declare module.exports: any;
}

declare module 'proton-native/bin/index' {
  declare module.exports: any;
}

declare module 'proton-native/bin/react-components/Area' {
  declare module.exports: any;
}

declare module 'proton-native/bin/react-components/Box' {
  declare module.exports: any;
}

declare module 'proton-native/bin/react-components/index' {
  declare module.exports: any;
}

declare module 'proton-native/bin/react-components/Menu' {
  declare module.exports: any;
}

declare module 'proton-native/bin/react-components/Picker' {
  declare module.exports: any;
}

declare module 'proton-native/bin/react-components/RadioButtons' {
  declare module.exports: any;
}

declare module 'proton-native/bin/react-components/Separator' {
  declare module.exports: any;
}

declare module 'proton-native/bin/react-components/TextInput' {
  declare module.exports: any;
}

declare module 'proton-native/bin/reconciler/index' {
  declare module.exports: any;
}

declare module 'proton-native/bin/render/index' {
  declare module.exports: any;
}

declare module 'proton-native/bin/testRenderer' {
  declare module.exports: any;
}

declare module 'proton-native/bin/utils/createElement' {
  declare module.exports: any;
}

declare module 'proton-native/bin/utils/styleToYoga' {
  declare module.exports: any;
}

// Filename aliases
declare module 'proton-native/bin/components/App.js' {
  declare module.exports: $Exports<'proton-native/bin/components/App'>;
}
declare module 'proton-native/bin/components/Area.js' {
  declare module.exports: $Exports<'proton-native/bin/components/Area'>;
}
declare module 'proton-native/bin/components/Button.js' {
  declare module.exports: $Exports<'proton-native/bin/components/Button'>;
}
declare module 'proton-native/bin/components/Checkbox.js' {
  declare module.exports: $Exports<'proton-native/bin/components/Checkbox'>;
}
declare module 'proton-native/bin/components/ColorButton.js' {
  declare module.exports: $Exports<'proton-native/bin/components/ColorButton'>;
}
declare module 'proton-native/bin/components/Combobox.js' {
  declare module.exports: $Exports<'proton-native/bin/components/Combobox'>;
}
declare module 'proton-native/bin/components/DesktopComponent.js' {
  declare module.exports: $Exports<'proton-native/bin/components/DesktopComponent'>;
}
declare module 'proton-native/bin/components/Dialog.js' {
  declare module.exports: $Exports<'proton-native/bin/components/Dialog'>;
}
declare module 'proton-native/bin/components/EditableCombobox.js' {
  declare module.exports: $Exports<'proton-native/bin/components/EditableCombobox'>;
}
declare module 'proton-native/bin/components/Entry.js' {
  declare module.exports: $Exports<'proton-native/bin/components/Entry'>;
}
declare module 'proton-native/bin/components/FontButton.js' {
  declare module.exports: $Exports<'proton-native/bin/components/FontButton'>;
}
declare module 'proton-native/bin/components/Form.js' {
  declare module.exports: $Exports<'proton-native/bin/components/Form'>;
}
declare module 'proton-native/bin/components/Grid.js' {
  declare module.exports: $Exports<'proton-native/bin/components/Grid'>;
}
declare module 'proton-native/bin/components/Group.js' {
  declare module.exports: $Exports<'proton-native/bin/components/Group'>;
}
declare module 'proton-native/bin/components/HorizontalBox.js' {
  declare module.exports: $Exports<'proton-native/bin/components/HorizontalBox'>;
}
declare module 'proton-native/bin/components/HorizontalSeparator.js' {
  declare module.exports: $Exports<'proton-native/bin/components/HorizontalSeparator'>;
}
declare module 'proton-native/bin/components/index.js' {
  declare module.exports: $Exports<'proton-native/bin/components/index'>;
}
declare module 'proton-native/bin/components/MenuBar.js' {
  declare module.exports: $Exports<'proton-native/bin/components/MenuBar'>;
}
declare module 'proton-native/bin/components/MultilineEntry.js' {
  declare module.exports: $Exports<'proton-native/bin/components/MultilineEntry'>;
}
declare module 'proton-native/bin/components/PasswordEntry.js' {
  declare module.exports: $Exports<'proton-native/bin/components/PasswordEntry'>;
}
declare module 'proton-native/bin/components/ProgressBar.js' {
  declare module.exports: $Exports<'proton-native/bin/components/ProgressBar'>;
}
declare module 'proton-native/bin/components/RadioButton.js' {
  declare module.exports: $Exports<'proton-native/bin/components/RadioButton'>;
}
declare module 'proton-native/bin/components/Root.js' {
  declare module.exports: $Exports<'proton-native/bin/components/Root'>;
}
declare module 'proton-native/bin/components/Slider.js' {
  declare module.exports: $Exports<'proton-native/bin/components/Slider'>;
}
declare module 'proton-native/bin/components/Spinbox.js' {
  declare module.exports: $Exports<'proton-native/bin/components/Spinbox'>;
}
declare module 'proton-native/bin/components/Tab.js' {
  declare module.exports: $Exports<'proton-native/bin/components/Tab'>;
}
declare module 'proton-native/bin/components/Text.js' {
  declare module.exports: $Exports<'proton-native/bin/components/Text'>;
}
declare module 'proton-native/bin/components/VerticalBox.js' {
  declare module.exports: $Exports<'proton-native/bin/components/VerticalBox'>;
}
declare module 'proton-native/bin/components/VerticalSeparator.js' {
  declare module.exports: $Exports<'proton-native/bin/components/VerticalSeparator'>;
}
declare module 'proton-native/bin/components/View.js' {
  declare module.exports: $Exports<'proton-native/bin/components/View'>;
}
declare module 'proton-native/bin/components/Window.js' {
  declare module.exports: $Exports<'proton-native/bin/components/Window'>;
}
declare module 'proton-native/bin/constants/types.js' {
  declare module.exports: $Exports<'proton-native/bin/constants/types'>;
}
declare module 'proton-native/bin/index.js' {
  declare module.exports: $Exports<'proton-native/bin/index'>;
}
declare module 'proton-native/bin/react-components/Area.js' {
  declare module.exports: $Exports<'proton-native/bin/react-components/Area'>;
}
declare module 'proton-native/bin/react-components/Box.js' {
  declare module.exports: $Exports<'proton-native/bin/react-components/Box'>;
}
declare module 'proton-native/bin/react-components/index.js' {
  declare module.exports: $Exports<'proton-native/bin/react-components/index'>;
}
declare module 'proton-native/bin/react-components/Menu.js' {
  declare module.exports: $Exports<'proton-native/bin/react-components/Menu'>;
}
declare module 'proton-native/bin/react-components/Picker.js' {
  declare module.exports: $Exports<'proton-native/bin/react-components/Picker'>;
}
declare module 'proton-native/bin/react-components/RadioButtons.js' {
  declare module.exports: $Exports<'proton-native/bin/react-components/RadioButtons'>;
}
declare module 'proton-native/bin/react-components/Separator.js' {
  declare module.exports: $Exports<'proton-native/bin/react-components/Separator'>;
}
declare module 'proton-native/bin/react-components/TextInput.js' {
  declare module.exports: $Exports<'proton-native/bin/react-components/TextInput'>;
}
declare module 'proton-native/bin/reconciler/index.js' {
  declare module.exports: $Exports<'proton-native/bin/reconciler/index'>;
}
declare module 'proton-native/bin/render/index.js' {
  declare module.exports: $Exports<'proton-native/bin/render/index'>;
}
declare module 'proton-native/bin/testRenderer.js' {
  declare module.exports: $Exports<'proton-native/bin/testRenderer'>;
}
declare module 'proton-native/bin/utils/createElement.js' {
  declare module.exports: $Exports<'proton-native/bin/utils/createElement'>;
}
declare module 'proton-native/bin/utils/styleToYoga.js' {
  declare module.exports: $Exports<'proton-native/bin/utils/styleToYoga'>;
}
